## Critical Role Statistical Visualiser
***

### What is this application?

This is a web application created to enable interactive exploration of data collected for the show [Critical Role](https://critrole.com/). The application visualises and models data regarding dice rolls, damage dealt, healing given, among much more. It is a continuous work-in-progress, and more features will be progressively added. 


### How do I use it?

Navigate through the app using the tabs at the top. Further details and instructions are provided on each tab. A high level overview of what each does presented below:

* __SPELLCASTING ANALYSIS__ Presents visualisations on spell usage by spell level and character.
* __CHARACTER ANALYSIS__ Presents character-level analysis and visualisation of dice roll data.
* __POTION ANALYSIS__ Presents visualisations of potion administration by character.
* __MONETARY ANALYSIS__ Presents analysis of coins gained and paid by episode.


### Who made it?

This application was built by Trent Henderson of [Orbisant Analytics](https://www.orbisantanalytics.com/). Trent is a data scientist from Brisbane, Australia, and can be found on Twitter [@trentlikesstats](https://twitter.com/trentlikesstats) or by [email](trent.henderson1@outlook.com).


### Where did the data come from?

All data is sourced from [Crit Role Stats](https://www.critrolestats.com/).


### Where did the artwork come from?

Official Mighty Nein artwork created by [@ornerine](https://twitter.com/ornerine) and sourced from [Critical Role website](https://critrole.com/hype-new-official-mighty-nein-character-art-by-ariana-orner/).


### How can I log an issue or contribute?

If you have a GitHub account, you can log an issue or contribute to application development at the [repository](https://github.com/hendersontrent/crit-role-webtool).

### What are the future plans for the application?

Currently, only data for The Mighty Nein is used in the app. It is intended that Vox Machina data will be added. Other creative data visualisations and statistical analyses for both campaigns are also likely to be added.
